### ISSUE TITLE
bash script를 사용여부

### ISSUE THREAD

**Issue by dispiny** [ItSeong/bash_Shell#1]
꼭 해야합니까?

굳이 필수는 아니라 생각이 듭니다.

**Comment by dispiny** [comment]
알 겠습니까.

**Comment by dispiny** [comment]
하.... 취업 망해라

**Comment by yseongjang** [comment]
![image](https://user-images.githubusercontent.com/89840576/131481575-f3f8fa7a-510d-4615-ae4b-179c9e5f895b.png)
